# Generated by Django 5.1 on 2024-08-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestModel',
            new_name='ItemModel',
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='title',
            new_name='name',
        ),
    ]
