# Generated by Django 5.1.2 on 2024-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(upload_to='course_pictures/')),
                ('description', models.TextField()),
                ('syllabus', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
