# Generated by Django 5.1.2 on 2024-10-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCourses', '0002_course_delete_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
