# Generated by Django 5.1.2 on 2024-10-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalApp', '0003_alter_assignments_options_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todos', 'verbose_name_plural': 'todos'},
        ),
    ]
