# Generated by Django 5.1.2 on 2024-10-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_attempted_at_quizattempt_date_attempted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizattempts', to='quiz.quiz'),
        ),
    ]
